### ISSUE TITLE
Modifications to model recipe

### ISSUE THREAD

**Issue by spflueger** [ComPWA/tensorwaves#69]
I think we can apply a small change to the recipe here:
```yaml
DecayParticle:
  Name: J/psi
  Helicity: -1
DecayProducts:
  Particle:
    - Name: f2(1950)
      FinalState: [3, 4]
      Helicity: 0.0
    - Name: gamma
      FinalState: 2
      Helicity: -1
```
can just become
```yaml
DecayParticle:
  Name: J/psi
  Helicity: -1
DecayProducts:
  - Name: f2(1950)
    FinalState: [3, 4]
    Helicity: 0.0
  - Name: gamma
    FinalState: 2
    Helicity: -1
```
and we can write
```python
recipe["DecayProducts"]
```

_Originally posted by @redeboer in https://github.com/ComPWA/tensorwaves/pull/66_

**Comment by spflueger** [comment]
In a similar manner I also propose the following improvements for the model file

```yml
NormalizedIntensity:
  IncoherentIntensity:
      - CoherentIntensity:
        Component: coherent_J/psi_-1_to_gamma_-1+pi0_0+pi0_0
        Amplitudes:
          CoefficientAmplitude:
            Component: J/psi_-1_to_f2(1270)_0+gamma_-1;f2(1270)_0_to_pi0_0+pi0_0;
            Parameters:
              Magnitude: *par1
              Phase: *par2
            SequentialAmplitude:
                - HelicityDecay:
                  DecayParticle:
                    Name: J/psi
                    Helicity: -1
                  DecayProducts:
                      - Name: f2(1270)
                        FinalState: [3, 4]
                        Helicity: 0.0
                      - Name: gamma
                        FinalState: 2
                        Helicity: -1
                - HelicityDecay:
                  DecayParticle:
                    Name: f2(1270)
                    Helicity: 0.0
                  DecayProducts:
                      - Name: pi0
                        FinalState: 3
                        Helicity: 0
                      - Name: pi0
                        FinalState: 4
                        Helicity: 0
                  RecoilSystem:
                    RecoilFinalState: 2
....
```
